# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


#' @useDynLib Blackjack, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

create_deck_cpp <- function() {
  .Call("_Blackjack_create_deck_cpp", PACKAGE = "Blackjack")
}
