# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_score_hand <- function(hand) {
    .Call(`_Blackjack_cpp_score_hand`, hand)
}

